train: ../train/images
val: ../valid/images
test: ../test/images

nc: 1
names: ["fracture"]

roboflow:
  workspace: project-iejfy
  project: one-jp4om
  version: 3
  license: CC BY 4.0
  url: https://universe.roboflow.com/project-iejfy/one-jp4om/dataset/3
